---
output: pdf_document
editor_options: 
  chunk_output_type: inline
author: "Zach Bogart"
title: "Advent of Code 2020"
---

# Day 2: Password Philosophy

https://adventofcode.com/2020/day/2

```{r include=FALSE}
library(tidyverse)
```

```{r message=FALSE}
input = read_delim("inputs/02-input.txt", delim = "\n", col_names = "text")
```

## Part 1

- split up the input
- get count of letter in password
- filter by count being within specified range

```{r}
df = input %>% 
  # split up input
  separate(text, sep = ": ", into = c("directions", "password")) %>% 
  separate(directions, sep = " ", into = c("range", "letter")) %>% 
  separate(range, sep = "-", into = c("range_lo", "range_hi"), convert = TRUE)
```

```{r}
part_1 = df %>% 
  # add count
  mutate(count = str_count(password, letter)) %>% 
  # filter if between range values
  rowwise() %>% 
  filter(between(count, range_lo, range_hi))

nrow(part_1)
```

\newpage

## Part 2

- get letters at index of string (R uses one-indexing so simple enough)
- check XOR for each index equaling the valid letter

```{r}
# extract substrings and take XOR
part_2 = df %>% 
  mutate(first = str_sub(password, range_lo, range_lo),
         second = str_sub(password, range_hi, range_hi),
         valid = xor(first == letter, second == letter))

part_2 %>% 
  filter(valid) %>% 
  nrow()
```

