---
author: "Zach Bogart"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE, eval=FALSE}
# run this chunk to render
day <- 1
day_title <- "Sonar Sweep"

day_str <- stringr::str_pad(day, 2, pad = "0")
rmarkdown::render(input = paste0("2021/code/", day_str, ".Rmd"), 
                  output_dir = paste0("2021/", day),
                  output_file = "index.html")
```

---
title: "`r paste0("AoC 2021: Day ", day)`"
---

# Day `r day`: `r day_title`

[Click for Problem Statement](`r paste0("https://adventofcode.com/2021/day/", day)`)

[Back to 2021](/advent_of_code/2021/)

---

```{r message=FALSE}
library(tidyverse)
library(here)
```

```{r}
input <- tibble(first = as.numeric(read_lines(here("2021/inputs/01-input.txt"))))
```

## Part 1

```{r}

part_1 <- input %>% 
  mutate(prev = lag(first)) %>% 
  select(prev, first) %>% 
  mutate(change = first > prev) %>% 
  fill(change, .direction = "up")

part_1 %>% 
  summarise(sum(change))

```

## Part 2

```{r}
part_2 <- input %>% 
  mutate(second = lag(first),
         third = lag(second)) %>% 
  mutate(total = first + second + third) %>% 
  mutate(change = total > lag(total))

part_2 %>% 
  summarise(sum(change, na.rm = TRUE))

```

