---
title: "AoC 2021"
author: "Zach Bogart"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE, eval=FALSE}
library(here)
library(emo)

rmarkdown::render(input = here("2021/code", "2021_index.Rmd"), 
                  output_dir = "2021/",
                  output_file = "index.html")
```


- [Day 1](1/)
<!-- - [Day 2](2/) -->
<!-- - [Day 3](3/) -->
<!-- - [Day 4](4/) -->
<!-- - [Day 5](5/) -->
<!-- - [Day 6](6/) -->
<!-- - [Day 7](7/) -->
<!-- - [Day 8](8/) -->
<!-- - [Day 9](9/) -->
<!-- - [Day 10](10/) -->
<!-- - [Day 11](11/) -->
<!-- - [Day 12](12/) -->
<!-- - [Day 13](13/) -->
<!-- - [Day 14](14/) -->
<!-- - [Day 15](15/) -->
<!-- - [Day 16](16/) -->
<!-- - [Day 17](17/) -->
<!-- - [Day 18](18/) -->
<!-- - [Day 19](19/) -->
<!-- - [Day 20](20/) -->
<!-- - [Day 21](21/) -->
<!-- - [Day 22](22/) -->
<!-- - [Day 23](23/) -->
<!-- - [Day 24](24/) -->
<!-- - [Day 25](25/) -->

---

[zachbogart.com]("https://zachbogart.com/")

`r emo::ji("christmas_tree")`